services:
  php-cli:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"
      DATABASE_HOST: oracle
      DATABASE_PORT: 1521
      DATABASE_NAME: symfony
      DATABASE_USER: symfony
      DATABASE_PASSWORD: symfony
      MAILER_TRANSPORT: smtp
      MAILER_HOST: mailhog
      MAILER_PORT: 1025
      MAILER_USER: ""
      MAILER_PASSWORD: ""
      APP_SECRET: ThisTokenIsNotSoSecretChangeIt
  php-web:
    container_name: web
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t web web/app_dev.php
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"
      DATABASE_HOST: oracle
      DATABASE_PORT: 1521
      DATABASE_NAME: symfony
      DATABASE_USER: symfony
      DATABASE_PASSWORD: symfony
      MAILER_TRANSPORT: smtp
      MAILER_HOST: mailhog
      MAILER_PORT: 1025
      MAILER_USER: ""
      MAILER_PASSWORD: ""
      APP_SECRET: ThisTokenIsNotSoSecretChangeIt
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_DATABASE: symfony
      APP_USER: symfony
      APP_USER_PASSWORD: symfony
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    shm_size: 1g
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    environment:
      MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    volumes:
      - ./data:/data:rw
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  oracle-data:
