services:
  php-cli:
    container_name: cli
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/symfony
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"
  php-web:
    container_name: web
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/symfony
    command: php -S 0.0.0.0:8000 -t web
    ports:
      - "8000:8000"
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"