AppBundle\Entity\Insight:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InsightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        severity:
            type: string
            length: '10'
        message:
            type: string
            length: 255
        revenueAtRiskInCents:
            type: string
            length: 255
            column: revenue_at_risk_in_cents
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks:
        prePersist: [ onPreCreatedAt ]
    manyToOne:
        charge:
            targetEntity: AppBundle\Entity\Charge
            inversedBy: insights
            joinColumn:
                name: charge_id
                referencedColumnName: id
        rule:
            targetEntity: AppBundle\Entity\Rule
            inversedBy: insights
            joinColumn:
                name: rule_id
                referencedColumnName: id