AppBundle\Entity\Charge:
  properties:
    payerType:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\EnumValue:
          enumClass: AppBundle\Enums\ChargePayerTypeEnum
          message: 'Invalid payer type.'
