AppBundle\Entity\Charge:
  properties:
    procedureCode:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\EnumValue:
          enumClass: AppBundle\Enums\ChargeProcedureCodeEnum
          message: 'Invalid procedure code.'

    payerType:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\EnumValue:
          enumClass: AppBundle\Enums\ChargeProcedureCodeEnum
          message: 'Invalid payer type.'
