AppBundle\Entity\Insight:
  properties:
    severity:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\EnumValue:
          enumClass: AppBundle\Enums\InsightSeverityEnum
          message: 'Invalid severity.'
