AppBundle\Entity\Rule:
  properties:
    type:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\EnumValue:
          enumClass: AppBundle\Enums\RuleTypeEnum
          message: 'Invalid rule type.'
